name: ai-final
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10.6
  - poetry
  - pip
  - numpy
  - pandas
  - scikit-learn
  - lightgbm
  - bokeh
  - pip:
    - finance-datareader
    - fastapi
    - uvicorn