name: ai-final
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10.6
  - pip
  - numpy
  - pandas
  - scikit-learn
  - lightgbm
  - bokeh
  - beautifulsoup4
  - black
  - matplotlib
  - plotly
  - jupyter
  - pip:
    - finance-datareader
    - fastapi
    - uvicorn