import "./globals.css";
import { Inter } from "@next/font/google";
import Head from "next/head";
const inter = Inter();

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <Head>
        <title>AI Final</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="bg-gray-50">{children}</body>
    </>
  );
}
